# Generated by Django 5.1.4 on 2024-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_bitacora_aprendiz_remove_bitacora_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='contrasena',
            field=models.CharField(max_length=200, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='usuario',
            field=models.CharField(max_length=200, null=True, verbose_name='Usuario'),
        ),
    ]
