# Generated by Django 5.1.4 on 2024-12-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='numero_telefono',
            new_name='num_telefono',
        ),
    ]
