# Generated by Django 5.1.4 on 2025-01-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_numero_telefono_empresa_num_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AlterModelOptions(
            name='detallebitacora',
            options={'verbose_name': 'DetalleBitácora', 'verbose_name_plural': 'DetalleBitácoras'},
        ),
        migrations.AlterModelTable(
            name='detallebitacora',
            table='DetalleBitacora',
        ),
    ]
