# Generated by Django 5.1.4 on 2025-01-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_empresa_alter_detallebitacora_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='imagen',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='bitacora',
            field=models.FileField(null=True, upload_to='bitacoras/', verbose_name='Archivo'),
        ),
    ]
