# Generated by Django 5.1.7 on 2025-03-31 13:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='linked_company',
            field=models.CharField(max_length=100, verbose_name='Empresa Vinculada'),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='productive_stage_start',
            field=models.DateField(verbose_name='Inicio Etapa Productiva'),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='record_number',
            field=models.CharField(max_length=20, verbose_name='Número de Ficha'),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='school_stage_start',
            field=models.DateField(verbose_name='Inicio Etapa Lectiva'),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='training_program',
            field=models.CharField(max_length=100, verbose_name='Programa de Formación'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='linked_apprentices',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'apprentice'}, related_name='assigned_instructors', to=settings.AUTH_USER_MODEL, verbose_name='Aprendices Vinculados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ti', 'Tarjeta de Identidad'), ('ce', 'Cédula de Extranjería'), ('passport', 'Pasaporte')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener más de 9 dígitos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('apprentice', 'Aprendiz'), ('instructor', 'Instructor')], max_length=10),
        ),
    ]
