# Generated by Django 5.1.7 on 2025-03-31 13:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_apprenticeprofile_linked_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='linked_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='productive_stage_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='record_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='school_stage_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='apprenticeprofile',
            name='training_program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='linked_apprentices',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'apprentice'}, related_name='assigned_instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('cc', 'Citizenship Card'), ('ti', 'Identity Card'), ('ce', 'Foreigner ID'), ('passport', 'Passport')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('apprentice', 'Apprentice'), ('instructor', 'Instructor')], max_length=10),
        ),
    ]
